# Generated by Django 2.1a1 on 2018-06-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180604_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='total_price',
        ),
    ]
